---
services:
  gyre-clone:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: gyre-clone
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - "127.0.0.1:9999:3000"
    environment:
      TZ: "Asia/Tokyo"
    env_file:
      - .env.local
    volumes:
      - ./data:/app/data

  mongo:
    image: mongo:4.4.18
    container_name: mongo
    restart: always
    ports:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: gyre-world-reflector
    volumes:
      - data:/data/db

volumes:
  data: {}
